# -*- coding: utf-8 -*-
"""Credit_Card_Fraud_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mWEqTBzcnxktDrwSEpAU91BGvcCYLIbP
"""

# Credit Card Fraud Detection Project
# Using Random Forest and XGBoost

# Importing required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, precision_score, recall_score, average_precision_score
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# ---------------------------------------------------
# 1. Data Loading & Cleaning
# ---------------------------------------------------

# Loading the dataset
print("Loading data...")
data = pd.read_csv("creditcard.csv")

# FIX: Drop rows with missing values to prevent "Input y contains NaN" error
# Dropping rows where the target 'Class' is missing
data = data.dropna(subset=["Class"])
# Filling any remaining missing feature values with 0 (or you can use .dropna() to remove them)
data = data.fillna(0)

# Scaling Amount and Time columns
scaler = StandardScaler()
data["Amount"] = scaler.fit_transform(data[["Amount"]])
data["Time"] = scaler.fit_transform(data[["Time"]])

# Splitting dataset into features and target
X = data.drop("Class", axis=1)
y = data["Class"]

# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"Training set size: {X_train.shape[0]}")
print(f"Testing set size: {X_test.shape[0]}")

# ---------------------------------------------------
# 2. Random Forest Model
# ---------------------------------------------------

print("\n========== Random Forest Model ==========")

# Creating Random Forest classifier with balanced class weights
random_forest = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced", # Upgraded: Penalizes missing the minority class
    n_jobs=-1 # Uses all CPU cores for faster training
)

# Training the model
print("Training Random Forest...")
random_forest.fit(X_train, y_train)

# Making predictions
rf_predictions = random_forest.predict(X_test)
# Getting probabilities for AUPRC
rf_probs = random_forest.predict_proba(X_test)[:, 1]

# Evaluation Metrics
print("\n--- Random Forest Performance ---")
print(f"Precision (Fake flagged as fraud): {precision_score(y_test, rf_predictions):.4f}")
print(f"Recall (Actual fraud caught): {recall_score(y_test, rf_predictions):.4f}")
print(f"AUPRC (Precision-Recall Area): {average_precision_score(y_test, rf_probs):.4f}")

print("\nClassification Report:")
print(classification_report(y_test, rf_predictions))

# ---------------------------------------------------
# 3. XGBoost Model
# ---------------------------------------------------

print("\n========== XGBoost Model ==========")

# Calculate ratio for scale_pos_weight
# Ratio = count(negative examples) / count(positive examples)
ratio = float(np.sum(y_train == 0)) / np.sum(y_train == 1)

# Creating XGBoost classifier with scale_pos_weight
xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=4,
    random_state=42,
    eval_metric='logloss',
    scale_pos_weight=ratio # Upgraded: Forces XGBoost to care about fraud cases
)

# Training the model
print("Training XGBoost...")
xgb_model.fit(X_train, y_train)

# Making predictions
xgb_predictions = xgb_model.predict(X_test)
# Getting probabilities for AUPRC
xgb_probs = xgb_model.predict_proba(X_test)[:, 1]

# Evaluation Metrics
print("\n--- XGBoost Performance ---")
print(f"Precision (Fake flagged as fraud): {precision_score(y_test, xgb_predictions):.4f}")
print(f"Recall (Actual fraud caught): {recall_score(y_test, xgb_predictions):.4f}")
print(f"AUPRC (Precision-Recall Area): {average_precision_score(y_test, xgb_probs):.4f}")

print("\nClassification Report:")
print(classification_report(y_test, xgb_predictions))

# ---------------------------------------------------
# 4. Visualizing Results
# ---------------------------------------------------

# Set up the figure for side-by-side confusion matrices
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Random Forest Matrix
rf_matrix = confusion_matrix(y_test, rf_predictions)
sns.heatmap(rf_matrix, annot=True, fmt='d', ax=axes[0], cmap='Blues')
axes[0].set_title("Random Forest Confusion Matrix")
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("Actual")

# XGBoost Matrix
xgb_matrix = confusion_matrix(y_test, xgb_predictions)
sns.heatmap(xgb_matrix, annot=True, fmt='d', ax=axes[1], cmap='Oranges')
axes[1].set_title("XGBoost Confusion Matrix")
axes[1].set_xlabel("Predicted")
axes[1].set_ylabel("Actual")

plt.tight_layout()
plt.show()